/**
 * \mainpage
 * \section Author
 * @author Jason Kulk
 *
 * \section Copyright
 * Version : $Id$
 *
 * \section Description
 *
 * This file was generated by Aldebaran Robotics ModuleGenerator
 */

#ifndef _WIN32
#include <signal.h>
#endif

#include "altypes.h"
#include "alxplatform.h"
#include "walkoptimiser.h"
#include "alptr.h"
#include "albroker.h"
#include "almodule.h"
#include "albrokermanager.h"

using namespace std;
using namespace AL;

//<EXE_INCLUDE> don't remove this comment
#include "jwalk.h"

//</EXE_INCLUDE> don't remove this comment

//<ODECLAREINSTANCE> don't remove this comment

//</ODECLAREINSTANCE> don't remove this comment


#ifdef JASON_IS_REMOTE_OFF

#ifdef _WIN32
    #error You can not compile jason for Windows
#else
#define ALCALL
#endif

#ifdef __cplusplus
extern "C"
{
#endif


ALCALL int _createModule( ALPtr<ALBroker> pBroker )
{      
  // init broker with the main broker inctance 
  // from the parent executable
  ALBrokerManager::setInstance(pBroker->fBrokerManager.lock());
  ALBrokerManager::getInstance()->addBroker(pBroker);

    
  // create modules instance
//<OGETINSTANCE> don't remove this comment
ALModule::createModule<JWalk>(pBroker,"JWalk" );

//</OGETINSTANCE> don't remove this comment 

  return 0;
}

ALCALL int _closeModule(  )
{
  // Delete module instance
//<OKILLINSTANCE> don't remove this comment

//</OKILLINSTANCE> don't remove this comment
 
  return 0;
}

# ifdef __cplusplus
}
# endif

#else
    #error You can not compile jason as remote
#endif

