/**
 * @author Jason Kulk
 *
 * Version : $
 *
 * This file was generated by Aldebaran Robotics ModuleGenerator
 */

#ifndef WALKOPTIMISER_H
#define WALKOPTIMISER_H

// ..::: Headers ::
// Add it here to be sure every file includes it
#include "alxplatform.h"
#include "config.h"
#include <fstream>
#include <sstream>
#include <albroker.h>
#include <almodule.h>
#include <altools.h>


#define ALVALUE_STRING( val ) ((val.getType() == ALValue::TypeString) ? std::string(val) : std::string("") )
#define ALVALUE_DOUBLE( val ) ((val.getType() == ALValue::TypeDouble || val.getType() == ALValue::TypeInt) ? double(val) : 0.0 )
#define ALVALUE_INT( val ) ((val.getType() == ALValue::TypeInt || val.getType() == ALValue::TypeDouble) ? int(val) : 0)

#endif // WALKOPTIMISER_H
